//
// AUTOGENERATED: DO NOT EDIT
// LSP Spec Version: 3.17.0
//

#pragma once

// clang-format off
#include <glaze/json.hpp>
#include "LSProtocol.h"
// clang-format on

// NOLINTBEGIN(readability-identifier-naming)
// clang-format off

template<>
struct glz::meta<lsp::SemanticTokenTypes> {
  using enum lsp::SemanticTokenTypes;
  static constexpr auto value = enumerate(
    "namespace", kNamespace,
    "type", kType,
    "class", kClass,
    "enum", kEnum,
    "interface", kInterface,
    "struct", kStruct,
    "typeParameter", kTypeparameter,
    "parameter", kParameter,
    "variable", kVariable,
    "property", kProperty,
    "enumMember", kEnummember,
    "event", kEvent,
    "function", kFunction,
    "method", kMethod,
    "macro", kMacro,
    "keyword", kKeyword,
    "modifier", kModifier,
    "comment", kComment,
    "string", kString,
    "number", kNumber,
    "regexp", kRegexp,
    "operator", kOperator,
    "decorator", kDecorator,
    "label", kLabel
  );
};

template<>
struct glz::meta<lsp::SemanticTokenModifiers> {
  using enum lsp::SemanticTokenModifiers;
  static constexpr auto value = enumerate(
    "declaration", kDeclaration,
    "definition", kDefinition,
    "readonly", kReadonly,
    "static", kStatic,
    "deprecated", kDeprecated,
    "abstract", kAbstract,
    "async", kAsync,
    "modification", kModification,
    "documentation", kDocumentation,
    "defaultLibrary", kDefaultlibrary
  );
};

template<>
struct glz::meta<lsp::DocumentDiagnosticReportKind> {
  using enum lsp::DocumentDiagnosticReportKind;
  static constexpr auto value = enumerate(
    "full", kFull,
    "unchanged", kUnchanged
  );
};

template<>
struct glz::meta<lsp::FoldingRangeKind> {
  using enum lsp::FoldingRangeKind;
  static constexpr auto value = enumerate(
    "comment", kComment,
    "imports", kImports,
    "region", kRegion
  );
};

template<>
struct glz::meta<lsp::UniquenessLevel> {
  using enum lsp::UniquenessLevel;
  static constexpr auto value = enumerate(
    "document", kDocument,
    "project", kProject,
    "group", kGroup,
    "scheme", kScheme,
    "global", kGlobal
  );
};

template<>
struct glz::meta<lsp::MonikerKind> {
  using enum lsp::MonikerKind;
  static constexpr auto value = enumerate(
    "import", kImport,
    "export", kExport,
    "local", kLocal
  );
};

template<>
struct glz::meta<lsp::CodeActionKind> {
  using enum lsp::CodeActionKind;
  static constexpr auto value = enumerate(
    "", kEmpty,
    "quickfix", kQuickfix,
    "refactor", kRefactor,
    "refactor.extract", kRefactorextract,
    "refactor.inline", kRefactorinline,
    "refactor.move", kRefactormove,
    "refactor.rewrite", kRefactorrewrite,
    "source", kSource,
    "source.organizeImports", kSourceorganizeimports,
    "source.fixAll", kSourcefixall,
    "notebook", kNotebook
  );
};

template<>
struct glz::meta<lsp::TraceValue> {
  using enum lsp::TraceValue;
  static constexpr auto value = enumerate(
    "off", kOff,
    "messages", kMessages,
    "verbose", kVerbose
  );
};

template<>
struct glz::meta<lsp::MarkupKind> {
  using enum lsp::MarkupKind;
  static constexpr auto value = enumerate(
    "plaintext", kPlaintext,
    "markdown", kMarkdown
  );
};

template<>
struct glz::meta<lsp::PositionEncodingKind> {
  using enum lsp::PositionEncodingKind;
  static constexpr auto value = enumerate(
    "utf-8", kUtf8,
    "utf-16", kUtf16,
    "utf-32", kUtf32
  );
};

template<>
struct glz::meta<lsp::FileOperationPatternKind> {
  using enum lsp::FileOperationPatternKind;
  static constexpr auto value = enumerate(
    "file", kFile,
    "folder", kFolder
  );
};

template<>
struct glz::meta<lsp::ResourceOperationKind> {
  using enum lsp::ResourceOperationKind;
  static constexpr auto value = enumerate(
    "create", kCreate,
    "rename", kRename,
    "delete", kDelete
  );
};

template<>
struct glz::meta<lsp::FailureHandlingKind> {
  using enum lsp::FailureHandlingKind;
  static constexpr auto value = enumerate(
    "abort", kAbort,
    "transactional", kTransactional,
    "textOnlyTransactional", kTextonlytransactional,
    "undo", kUndo
  );
};

template<>
struct glz::meta<lsp::TokenFormat> {
  using enum lsp::TokenFormat;
  static constexpr auto value = enumerate(
    "relative", kRelative
  );
};

// clang-format on
// NOLINTEND(readability-identifier-naming)

#include "LSProtocolCodecEx.h"
