import pathlib
from graphlib import TopologicalSorter

import generator.model as model

from .builder import SourceCodeBuilder, TypesRegistry
from .cpp_aliases import generate_type_aliases
from .cpp_enum import generate_enums
from .cpp_structs import generate_structs


def _write_types(reg: TypesRegistry, hdr_buf: SourceCodeBuilder) -> None:
  ordered_types = TopologicalSorter(
    {
      name: entry.dependencies
      for name, entry in reg.items()
      if name not in ["LSPArray", "LSPAny"]
    }
  ).static_order()

  for typename in ordered_types:
    if typename in ["LSPObject", "LSPArray", "LSPAny"]:
      continue
    hdr_buf += reg[typename].buf


def _write_heading(buf: SourceCodeBuilder, spec: model.LSPModel):
  buf.write("//")
  buf.write("// AUTOGENERATED: DO NOT EDIT")
  buf.write(f"// LSP Spec Version: {spec.metaData.version}")
  buf.write("//")
  buf.newline()


def _build_header(spec: model.LSPModel, reg: TypesRegistry):
  buf = SourceCodeBuilder()
  #
  _write_heading(buf, spec)
  buf.write("#pragma once")
  buf.newline()
  for incl in (
    "cstdint",
    "optional",
    "string",
    "string_view",
    "tuple",
    "variant",
    "unordered_map",
    "vector",
  ):
    buf.write(f"#include <{incl}>")
  buf.newline()
  buf.write("// NOLINTBEGIN(readability-identifier-naming)")
  buf.newline()
  buf.write("namespace lsp {")
  buf.newline()
  buf.write("#ifdef LSPROTOCOL_CODEC")
  buf.write("using LSPAny = glz::generic;")
  buf.write("#else")
  buf.write("struct LSPAny {};")
  buf.write("#endif")
  buf.write("using LSPArray = std::vector<LSPAny>;")
  buf.write("using LSPObject = LSPAny;")
  buf.write("struct LiteralStub {};  // TODO")
  buf.newline()
  _write_types(reg, buf)
  buf.newline()
  buf.write("}  // namespace lsp")
  buf.newline()
  for tp in reg.values():
    if tp.appendix:
      buf += tp.appendix
      buf.newline()
  buf.write("// NOLINTEND(readability-identifier-naming)")
  buf.newline()
  buf.write('#include "LSProtocolEx.h"')
  buf.newline()

  return buf.build()


def _build_codec(spec: model.LSPModel, reg: TypesRegistry):
  buf = SourceCodeBuilder()
  #
  _write_heading(buf, spec)
  buf.write("#pragma once")
  buf.newline()
  buf.write("// clang-format off")
  buf.write("#include <glaze/json.hpp>")
  buf.write('#include "LSProtocol.h"')
  buf.write("// clang-format on")
  buf.newline()
  buf.write("// NOLINTBEGIN(readability-identifier-naming)")
  buf.write("// clang-format off")
  buf.newline()
  for tp in reg.values():
    if tp.codec:
      buf += tp.codec
      buf.newline()
  buf.write("// clang-format on")
  buf.write("// NOLINTEND(readability-identifier-naming)")
  buf.newline()
  buf.write('#include "LSProtocolCodecEx.h"')
  buf.newline()

  return buf.build()


def generate_from_spec(spec: model.LSPModel, output_dir: str, test_dir: str) -> None:
  output_path = pathlib.Path(output_dir)
  if not output_path.exists():
    output_path.mkdir(parents=True, exist_ok=True)

  reg = TypesRegistry()
  reg |= generate_enums(spec)
  reg |= generate_type_aliases(spec)
  reg |= generate_structs(spec)

  (output_path / "include" / "LSProtocol.h").write_text(
    _build_header(spec, reg), encoding="utf-8"
  )
  (output_path / "include" / "LSProtocolCodec.h").write_text(
    _build_codec(spec, reg), encoding="utf-8"
  )
