function(enable_coverage_if_used)
  if(NOT VANADIUM_USE_COVERAGE)
    return()
  endif()

  # TODO: extract to a separate aux .cmake file if one will be needed
  function(collect_targets dir output)
    get_property(local_targets DIRECTORY ${dir} PROPERTY BUILDSYSTEM_TARGETS)
    get_property(subdirs DIRECTORY ${dir} PROPERTY SUBDIRECTORIES)
    foreach(subdir ${subdirs})
      collect_targets(${subdir} sub_targets)
      list(APPEND local_targets ${sub_targets})
    endforeach()
    set(${output} ${local_targets} PARENT_SCOPE)
  endfunction()
  collect_targets(${CMAKE_SOURCE_DIR} all_targets)

  foreach(t ${all_targets})
    get_target_property(type ${t} TYPE)
    if(NOT type MATCHES "EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY")
      continue()
    endif()

    get_target_property(dir ${t} SOURCE_DIR)
    if(dir MATCHES "^${PROJECT_SOURCE_DIR}")
      target_compile_options(${t} PRIVATE --coverage)
      target_link_options(${t} PRIVATE --coverage)
    endif()
  endforeach()
endfunction()
